### ISSUE TITLE
Client do not show paper correctly.

### ISSUE THREAD

**Issue by Sanquira** [Sanquira/Hexa#11]
Exception in thread "pool-1-thread-15" java.lang.NullPointerException
        at hexapaper.entity.Postava.clone(Postava.java:9
        at hexapaper.entity.Postava.clone(Postava.java:1)
        at hexapaper.gui.HraciPlocha.insertEntity(HraciPlocha.java:170)
        at hexapaper.network.server.ClientListeners$9.packetReceive(ClientListeners.java:139)
        at network.core.source.NetworkStorage$1.run(NetworkStorage.java:51)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by Sanquira** [comment]
Fixed in 47e231c2570af0a53f69396c2b8ca26c81dae32f
